---
- name: Common configuration
  hosts: pbs_master:pbs_clients:maui_master
  roles:
    - { role: iptables, default_input_policy: 'ACCEPT' }

- name: PBS masternode Playbook
  hosts: pbs_master
  tasks: 
    - include: common/tasks/nfs.yml
    - nfsexport: path=/home dest=/etc/exports clients="{{groups.pbs_clients}}" options=rw,no_root_squash,async
      notify: 
        - ensure nfs service is running
        - reload exports

    - include: pbs+maui/tasks/master.yml
    - include: cluster/tasks/packages.yml
  handlers:
    - include: slurm/handlers/main.yml
    - include: common/handlers/main.yml
    - include: pbs+maui/handlers/main.yml

- name: MAUI masternode Playbook
  hosts: maui_master
  tasks: 
    - include: pbs+maui/tasks/maui.yml
  handlers:
    - include: pbs+maui/handlers/main.yml

- name: PBS worker nodes Playbook
  hosts: pbs_clients
  tasks: 
    - include: common/tasks/nfs-clients.yml nfsserver={{groups.pbs_master[0]}} nfspath=/home nfsmount=/home nfsoptions=rw,async
    - include: pbs+maui/tasks/clients.yml
    - include: cluster/tasks/packages.yml
  handlers:
    - include: pbs+maui/handlers/main.yml

