---
- name: Slurm common Playbook
  hosts: slurm_master:slurm_clients
  vars:
    slurm_src_baseurl: "{{slurm_source_baseurl|default('http://www.schedmd.com/download/latest/')}}"
    slurm_src_filename: "{{slurm_source_filename|default('slurm-15.08.4.tar.bz2')}}"
    slurm_pkg_name: "{{slurm_package_name|default('slurm-15.08.4-1.el6.x86_64.rpm')}}"
  vars_files:
    - common/vars/main.yml
  roles:
    - { role: iptables, default_input_policy: 'ACCEPT' }
  tasks:
    - set_fact:
        slurm_name: slurm-llnl
        slurmdbd_name: slurm-llnl-slurmdbd
      when: is_debian_or_ubuntu
      tags: slurm

    - set_fact:
        slurm_name: slurm
        slurmdbd_name: slurmdbd
      when: is_centos
      tags: slurm

    - include: slurm/tasks/main.yml
    - include: cluster/tasks/packages.yml
  handlers:
    - include: common/handlers/main.yml
    - include: slurm/handlers/main.yml


- name: Slurm master Playbook
  hosts: slurm_master
  vars:
    slurmdbd_mysql_db: "{{slurm_mysql_db|default('slurm')}}"
    slurmdbd_mysql_user: "{{slurm_mysql_user|default('slurm')}}"
    slurmdbd_mysql_pwd: "{{slurm_mysql_pwd|default('ua7diKee')}}"
  vars_files:
    - common/vars/main.yml
  tasks: 
    - include: common/tasks/nfs.yml

    - nfsexport: path=/home dest=/etc/exports clients="{{groups.slurm_clients}}" options=rw,no_root_squash,async state=exported
      notify: 
        - ensure nfs service is running
        - reload exports

      tags:
        - nfs

    - include: slurm/tasks/master.yml
  handlers:
    - include: common/handlers/main.yml
    - include: slurm/handlers/main.yml

- name: Slurm worker nodes Playbook
  hosts: slurm_clients
  vars_files:
    - common/vars/main.yml
  tasks: 
    - include: common/tasks/nfs-clients.yml nfsserver={{groups.slurm_master[0]}} nfspath=/home nfsmount=/home
  handlers:
    - include: common/handlers/main.yml
    - include: slurm/handlers/main.yml

# Get infos with
# ansible -i hostsfile -m setup hostname
