---
- name: Unmount /etc/hosts in case we are running on docker
  action: shell umount /etc/hosts
  when: is_docker_container is defined
  ignore_errors: true

- name: Set /etc/hosts from Ansible hostgroups
  template:
    dest=/etc/hosts
    src=etc/hosts.j2
    owner=root
    group=root
