---
- name: Ensure all needed packages are installed
  only_if: $is_ubuntu
  action: apt pkg=$item state=installed update_cache=yes
  with_items:
    - default-jdk
    - sudo

- name: Install hadoop APT repository
  action: apt_repository repo=ppa:hadoop-ubuntu/stable
  only_if: $is_ubuntu
