# slurm-common/defaults/main.yml
---

SLURM_MASTER_HOST: "{{groups['slurm_master'][0]}}"
SLURM_MASTER_ADDR: "{{hostvars[SLURM_MASTER_HOST].ansible_default_ipv4.address}}"

# XXX: hard-code `localhost` for now so we do not have to change the
# port binding policy of MySQL/MariaDB, and not care about setting
# firewall rules for port 3306
SLURM_ACCOUNTING_HOST: "localhost"
SLURM_ACCOUNTING_DB_NAME: "slurm"
SLURM_ACCOUNTING_DB_USER: "slurm"
SLURM_ACCOUNTING_DB_PASS: "ua7diKee"