# hpc-common/tasks/main.yml
---

- name: Install common HPC software (Debian/Ubuntu)
  package:
    name:
      - build-essential
      - gfortran
      - libatlas-base-dev
      - libhdf5-dev
      - libhdf5-openmpi-dev
      - liblapack-dev
      - libnetcdf-dev
      - libopenblas-dev
      - sqlite3
    state: '{{ pkg_install_state }}'
  when: is_debian_compatible


- name: Install common HPC software (RHEL/CentOS)
  package:
    name:
      - atlas-devel
      - blas-devel
      - gcc-c++
      - gcc-gfortran
      - hdf5
      - hdf5-openmpi
      - make
      - netcdf-devel
    state: '{{ pkg_install_state }}'
  when: is_rhel_compatible
