language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install --upgrade setuptools"
  - "pip install pytest pytest-cov mock tox"
  - "pip install ."
script: py.test --cov=elasticluster
sudo: false
