---
- name: Ganglia frontend/collector Playbook
  hosts: ganglia_master
  sudo: yes
  tasks:
    - include: ganglia/tasks/server.yml
  tags:
    - ganglia
  handlers:
    - include: ganglia/handlers/main.yml

- name: Ganglia monitor Playbook
  hosts: ganglia_monitor
  sudo: yes
  tasks:
    - include: ganglia/tasks/client.yml
  handlers:
    - include: ganglia/handlers/main.yml
  tags:
    - ganglia
