---
- name: Slurm master Playbook
  hosts: slurm_master
  tasks: 
    - include: slurm/tasks/main.yml
    - include: slurm/tasks/nfs.yml
  handlers:
    - include: slurm/handlers/main.yml

- name: Slurm worker nodes Playbook
  hosts: slurm_clients
  tasks: 
    - include: slurm/tasks/main.yml
    - include: slurm/tasks/nfs-clients.yml
  handlers:
    - include: slurm/handlers/main.yml

# Get infos with
# ansible -i hostsfile -m setup hostname