---
- name: Ganglia frontend/collector Playbook
  hosts: ganglia_master
  tasks:
    - include: common/tasks/init-Debian.yml
    - include: ganglia/tasks/server.yml
  tags:
    - ganglia
  handlers:
    - include: ganglia/handlers/main.yml

- name: Ganglia monitor Playbook
  hosts: ganglia_monitor
  tasks:
    - include: common/tasks/init-Debian.yml
    - include: ganglia/tasks/client.yml
  handlers:
    - include: ganglia/handlers/main.yml
  tags:
    - ganglia
