---
- name: Slurm master Playbook
  hosts: slurm_master
  roles:
    - role: 'nfs-server'
      NFS_EXPORTS:
        - path: '/home'
          clients: "{{groups.slurm_workers}}"
    - slurm-master

      
- name: Slurm worker nodes Playbook
  hosts: slurm_workers:slurm_clients
  roles:
    - role: 'nfs-client'
      NFS_MOUNTS:
        - fs: '{{groups.slurm_master[0]}}:/home'
          mountpoint: '/home'
    - slurm-worker
