---

- name: Set variables (Debian/Ubuntu)
  set_fact:
    slurmctld_service_name: slurmctld
    slurmdbd_service_name: slurmdbd
  when: '{{is_debian_or_ubuntu}} and ({{is_debian_8_or_later}} or {{is_ubuntu_15_10_or_later}})'
  
- name: Set variables (older Debian/Ubuntu)
  set_fact:
    slurmctld_service_name: slurm-llnl
    slurmdbd_service_name: slurm-llnl-slurmdbd
  when: '{{is_debian_or_ubuntu}} and not ({{is_debian_8_or_later}} or {{is_ubuntu_15_10_or_later}})'
  
- name: Set variables (RHEL-compatible)
  set_fact:
    slurmctld_service_name: slurmctld
    slurmdbd_service_name: slurmdbd
  when: 'is_rhel_compatible'

  
- name: Install SLURM master packages (Debian/Ubuntu)
  package:
    pkg='{{item}}'
    state=latest
  with_items:
    - slurmctld
    - slurmdbd
  when: '{{is_debian_8_or_later}} or {{is_ubuntu_15_10_or_later}}'


- name: Install SLURM master packages (older Debian/Ubuntu)
  package:
    pkg='{{item}}'
    state=latest
  with_items:
    - slurm-llnl
    - slurm-llnl-slurmdbd
  when:
    '{{is_debian_or_ubuntu}} and not ({{is_debian_8_or_later}} or {{is_ubuntu_15_10_or_later}})'


- name: Install SLURM master packages (RHEL-compatible)
  package:
    name='{{item}}'
    state=latest
  with_items:
    - slurm
    - slurm-plugins
    - slurm-slurmdbd
    - slurm-slurmdb-direct
    - slurm-sql
  when: 'is_rhel_compatible'


- block:
  - name: Replace systemd unit file for SLURM services
    copy:
      dest='/usr/lib/systemd/system/{{item}}.service'
      src='usr/lib/systemd/system/{{item}}.service'
      owner=root
      group=root
      mode=0444
      backup=yes
    with_items:
      - slurmdbd
      - slurmctld
  - name: Reload systemd unit files
    command: |
      systemctl daemon-reload
    become: yes
  when: 'is_rhel7_compatible'


- name: Ensure `slurmdbd` is running
  tags: 
    - slurm
    - slurmdbd
  service:
    name='{{item}}'
    enabled=yes
    state=started
  with_items:
    - '{{slurmdbd_service_name}}'
