---
- name: install packages
  only_if: $is_centos
  action: yum pkg=$item state=latest
  with_items:
    - torque-server
    - maui

- name: Ensure pbs services are running
  only_if: $is_centos
  action: service name=$item state=started
  with_items:
    - trqauthd
    - pbs_server
    - maui

- name: Update node file
  action: template src=pbs+maui/templates/var/spool/torque/server_priv/nodes.j2
          dest=/var/spool/torque/server_priv/nodes
  notify: restart pbs_server

- name: copy default configuration file for pbs
  action: copy src=pbs+maui/files/qmgr.bootstrap dest=/var/spool/torque/server_priv/qmgr.bootstrap

- name: default configuration
  action: shell qmgr < /var/spool/torque/server_priv/qmgr.bootstrap