# Install and configure the MUNGE authentication service
---

- name: Install MUNGE (Debian/Ubuntu)
  tags:
    - slurm
    - munge
    - debian
  package:
    pkg=munge
    state=latest
  when:
    is_debian_compatible


- name: Install MUNGE (RHEL-compatible)
  tags:
    - slurm
    - munge
    - rhel
  package:
    pkg=slurm-munge
    state=latest
  when:
    is_rhel_compatible


- name: patch `/etc/default/munge` on Ubuntu 14.04
  tags:
    - slurm
    - munge
    - ubuntu
    - trusty
  lineinfile:
    dest='/etc/default/munge'
    line='OPTIONS="--force"'
    regexp='^OPTIONS='
    state=present
  when: is_ubuntu_trusty

  
- name: Configure MUNGE
  tags:
    - slurm
    - munge
  copy:
    src=etc/munge/munge.key
    dest=/etc/munge/munge.key
    owner=munge
    group=munge
    mode=0400
  notify: restart munge

  
- name: Ensure the MUNGE service is running
  tags:
    - slurm
    - munge
  service:
    name=munge
    enabled=yes
    state=started
