---

- name: reload iptables
  service:
    name='{{service["iptables"][ansible_os_family]}}'
    state=reloaded

- name: reload ip6tables
  service:
    name='{{service["ip6tables"][ansible_os_family]}}'
    state=reloaded

- name: restart iptables
  service:
    name='{{service["iptables"][ansible_os_family]}}'
    state=restarted

- name: restart ip6tables
  service:
    name='{{service["ip6tables"][ansible_os_family]}}'
    state=restarted
