---

- name: no-op
  debug:
    msg="Not reloading iptables -- not supported by {{service['iptables']}} service unit"

- name: reload iptables
  service:
    name='{{service["iptables"]}}'
    state=reloaded

- name: reload ip6tables
  service:
    name='{{service["ip6tables"]}}'
    state=reloaded

- name: restart iptables
  service:
    name='{{service["iptables"]}}'
    state=restarted

- name: restart ip6tables
  service:
    name='{{service["ip6tables"]}}'
    state=restarted
