---

- name: ensure {{item.mountpoint}} directory exists
  file:
    path={{item.mountpoint}}
    state=directory

- name: add to /etc/fstab
  mount:
    name='{{item.mountpoint}}'
    src='{{item.fs}}'
    fstype=nfs
    opts='{{item.options|default("rw,async")}}'
    state='{{item.state|default("mounted")}}'


- name: Allow NFS homes through SELinux
  command: |
    setsebool -P use_nfs_home_dirs=1
  when: '{{is_rhel_compatible}} and "{{item.mountpoint}}" == "/home"'
