---
# TEST: deleting files
# - action: shell rm -rf /var/lib/ceph/mon/ceph-ceph
#   tags:
#     - ceph

# - action: shell rm -rf /etc/ceph/ceph.mon.keyring
#   tags:
#     - ceph

# - action: shell rm -rf /etc/ceph/monmap
#   tags:
#     - ceph
# END TEST

- action: file dest=/var/lib/ceph/mon/ceph-${ceph-idx} state=directory
  tags:
    - ceph

# To do only on the *first* mon client
- name: Create keyring on the first mon node
  action: shell ceph-authtool /etc/ceph/ceph.mon.keyring --list | grep -A 1 '\[mon\.\]' | 
          tail -1 |sed 's/\s*key\s*=\s*//g' | grep =$ ||
          ceph-authtool /etc/ceph/ceph.mon.keyring --create-keyring --gen-key -n mon. -p --cap mon 'allow *' | tail -1 | grep =$
  register: mon_key
  only_if: '"$inventory_hostname" == "${groups.ceph_mon[0]}"'
  tags:
    - ceph

- name: Create key for client.admin on the first mon node
  action: shell ceph-authtool /etc/ceph/ceph.mon.keyring --list | grep -A 1 '\[client\.admin\]' | 
          tail -1 |sed 's/\s*key\s*=\s*//g' | grep =$ ||
          ceph-authtool /etc/ceph/ceph.mon.keyring --gen-key -n client.admin -p  --cap mon 'allow *' --cap osd 'allow *' --cap mds 'allow *' | grep =$
  register: client_admin_key 
  only_if: '"$inventory_hostname" == "${groups.ceph_mon[0]}"'
  tags:
    - ceph


# - name: Create key for client.bootstrap-osd on the first mon node
#   action: shell ceph-authtool /etc/ceph/ceph.mon.keyring --list | grep -A 1 '\[client\.bootstrap-osd\]' | 
#           tail -1 |sed 's/\s*key\s*=\s*//g' | grep =$ ||
#           ceph-authtool /etc/ceph/ceph.mon.keyring --gen-key -n client.bootstrap-osd -p --cap osd 'allow *' --cap mon 'allow *'| grep =$
#   register: client_admin_key 
#   only_if: '"$inventory_hostname" == "${groups.ceph_mon[0]}"'
#   tags:
#     - ceph


- name: Create key for MON.n on the first mon node
  action: shell idx=${hostvars.{$item}.ceph-idx};
          ceph-authtool /etc/ceph/ceph.mon.keyring --list | grep -A 1 "\[mon\.$idx\]" | 
          tail -1 |sed 's/\s*key\s*=\s*//g' | grep =$ ||
          ceph-authtool /etc/ceph/ceph.mon.keyring --gen-key -n mon.$idx -p --cap mon 'allow *' | grep =$
  only_if: '"$inventory_hostname" == "${groups.ceph_mon[0]}"'
  with_items: ${groups.ceph_mon}
  tags:
    - ceph

- name: Create key for OSD.n on the first mon node
  action: shell idx=${hostvars.{$item}.ceph-idx};
          ceph-authtool /etc/ceph/ceph.mon.keyring --list | grep -A 1 "\[osd\.$idx\]" | 
          tail -1 |sed 's/\s*key\s*=\s*//g' | grep =$ ||
          ceph-authtool /etc/ceph/ceph.mon.keyring --gen-key -n osd.$idx -p --cap osd 'allow *' --cap mon 'allow rwx'| grep =$
  only_if: '"$inventory_hostname" == "${groups.ceph_mon[0]}"'
  with_items: ${groups.ceph_osd}
  tags:
    - ceph

- name: Copy keyring to the mon nodes
  action: shell scp /etc/ceph/ceph.mon.keyring root@$item:/etc/ceph/keyring
  with_items: ${groups.ceph_mon}
  register: client_admin_key 
  only_if: '"$inventory_hostname" == "${groups.ceph_mon[0]}"'
  tags:
    - ceph

- name: copy keyring in /etc/ceph/keyring
  action: shell cp -a /etc/ceph/keyring /var/lib/ceph/mon/ceph-${ceph-idx}/keyring 
  tags:
    - ceph

- name: Copy keyring to the osd nodes
  action: shell scp /etc/ceph/ceph.mon.keyring root@$item:/etc/ceph/keyring
  with_items: ${groups.ceph_osd}
  register: client_admin_key 
  only_if: '"$inventory_hostname" == "${groups.ceph_mon[0]}"'
  tags:
    - ceph

- name: Create monmapfile
  action: shell  monmaptool --create --generate -c /etc/ceph/ceph.conf /etc/ceph/monmap
          creates=/etc/ceph/monmap
  tags:
    - ceph

- name: Create mon fs
  action: shell ceph-mon --mkfs -i ${ceph-idx} --monmap /etc/ceph/monmap --keyring /etc/ceph/keyring
          creates=/var/lib/ceph/mon/ceph-${ceph-idx}/store.db/CURRENT
  tags:
    - ceph

- name: Ensure ceph-mon is running
  action: service name=ceph state=started
  tags:
    - ceph

- name: Create OSDs
  action: shell ceph osd ls | egrep ^${hostvars.{$item}.ceph-idx}$ ||  ceph osd create
  with_items: ${groups.ceph_osd}
  only_if: '"$inventory_hostname" == "${groups.ceph_mon[0]}"'
  tags:
    - ceph

