---
# TEST
- name: unmount ephemeral disk
  action: shell umount /mnt ; true
  tags:
    - ceph
# END TEST

- name: create osd directory
  action: file dest=/var/lib/ceph/osd/ceph-${ceph-idx} state=directory
  tags:
    - ceph

- name: Check if device exists
  action: shell ceph-disk list | grep "/dev/vdb"
  ignore_errors: yes
  register: device_is_created
  tags:
    - ceph

- name: Ensure the filesystem is not mounted
  action: shell umount /dev/vdb1 ; true
  only_if: '"${device_is_created.stdout}".find("ceph data, prepared") == -1'
  tags:
    - ceph
    

- name: Prepare disk
  action: shell ceph-disk-prepare --zap-disk /dev/vdb
  only_if: '"${device_is_created.stdout}".find("ceph data, prepared") == -1'
  tags:
    - ceph

- name: Prepare to write whoami file
  action: shell umount /dev/vdb1; mount /dev/vdb1 /var/lib/ceph/osd/ceph-${ceph-idx}
  tags:
    - ceph

- name: Copy mon keyring
  action: shell cp -a /etc/ceph/keyring /var/lib/ceph/osd/ceph-${ceph-idx}/keyring
          creates=/var/lib/ceph/osd/ceph-${ceph-idx}/keyring
  tags:
    - ceph


# - name: Create whoami file
#   action: copy content=${ceph-idx} dest=/var/lib/ceph/osd/ceph-${ceph-idx}/whoami force=yes
#   tags:
#     - ceph
#     - test

# ceph-disk prepare does not create all the files needed by
# ceph-osd. Specifically, it does not create the whoami file
# (containing the id of the node) and the `current` dir. However, the
# ceph-osd --mkfs command does...

- name: Copy mon keyring
  action: shell ceph-osd -i ${ceph-idx}  -c /etc/ceph/ceph.conf -d --mkfs --mkjournal
          creates=/var/lib/ceph/osd/ceph-${ceph-idx}/current
  tags:
    - ceph

- name: Unmount ceph fs
  action: shell unmount /dev/vdb1 ; true
  tags:
    - ceph


- name: Ensure ceph-osd is running
  action: service name=ceph state=started
  tags:
    - ceph
