# Ensure additional packages are installed

- name: Ensure extra repositories are present (Ubuntu)
  apt_repository:
    repo="deb http://archive.ubuntu.com/ubuntu {{ansible_distribution_release}} universe multiverse"
    state=present
  when: is_ubuntu

- name: Ensure the APT package cache is updated
  apt:
    update_cache=yes
    cache_valid_time=0
  when: is_debian_or_ubuntu

- name: Install Ansible `apt` module dependencies
  # the `apt` module depends on both `aptitude` and `python-apt` to do
  # package-level work, so we need to resort to a raw invocation of `apt-get`
  command: apt-get install -y aptitude python-apt
  become: yes

- name: Upgrade all installed packages to latest version
  apt:
    upgrade=safe
  when: is_debian_or_ubuntu
  
- name: Ensure additional packages are installed
  apt:
    name={{item}}
    state=present
  with_items:
    - sysvinit-utils
    - software-properties-common
    - python-software-properties
    - python-pycurl
  when: is_debian_or_ubuntu
