---
#
# Ensure the node host name matches the Ansible inventory name
#

- name: Update `/etc/hostname`
  lineinfile:
    destfile='/etc/hostname'
    regexp='.*'
    line='{{inventory_hostname}}'
    create=yes
  when: is_debian_compatible

- name: Update HOSTNAME in file `/etc/sysconfig/network`
  lineinfile:
    destfile='/etc/sysconfig/network'
    regexp='^HOSTNAME='
    line='HOSTNAME={{inventory_hostname}}'
  when: is_rhel_compatible

- name: Set host name to Ansible "inventory name"
  hostname: 
    name='{{inventory_hostname}}'
