---
- name: Unmount /etc/hosts (Docker containers)
  action: shell umount /etc/hosts
  when: '{{ is_docker_container|default(False) }}'
  ignore_errors: true

- name: Set /etc/hosts from Ansible hostgroups
  template:
    dest=/etc/hosts
    src=etc/hosts.j2
    owner=root
    group=root
