---

- include: 'init-{{ansible_os_family}}.yml'
- include: hosts.yml hosts={{groups.all}}
- include: hostname.yml
- include: 'software-{{ansible_os_family}}.yml'
- include: ssh_host_based_authentication.yml
