---

- block:
    # These steps are needed for docker machines
    - name: Overwrite /sbin/initctl
      shell: dpkg-divert --local --rename --add /sbin/initctl creates=/sbin/initctl.distrib
      notify: kill-HUP sshd

    - name: Link /sbin/initctl to /bin/true
      file: src=/bin/true dest=/sbin/initctl state=link

  when: '({{is_debian_or_ubuntu}}) and {{is_docker_container|default(False)}}'


- name: Setup SSH known hosts file
  template:
    dest=/etc/ssh/ssh_known_hosts
    src=roles/common/templates/etc/ssh/ssh_known_hosts.j2
    owner=root
    group=root
    mode=0644

    
- name: Setup /etc/ssh/shosts.equiv file
  template:
    dest=/etc/ssh/shosts.equiv
    src=roles/common/templates/etc/ssh/shosts.equiv.j2
    owner=root
    group=root


- name: Setup /root/.shosts file
  template:
    dest=/root/.shosts
    src=roles/common/templates/etc/ssh/shosts.equiv.j2
    owner=root
    group=root

    
- name: Setup SSH host based authentication (server configuration file)
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='{{item.key}}.*'
    line="{{item.key}} {{item.value}}"
  with_items:
    - { key: "HostbasedAuthentication", value: 'yes' }
    - { key: "IgnoreRhosts",            value: 'no'  }
  notify: restart sshd

  
- name: Setup SSH host based authentication (server configuration file)
  lineinfile:
    dest=/etc/ssh/ssh_config
    regexp='{{item.key}}.*'
    line="{{item.key}} {{item.value}}"
  with_items:
    - { key: 'HostbasedAuthentication', value: 'yes' }
    - { key: 'EnableSSHKeysign',        value: 'yes' }
